<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'ID',
                'edit' => 1,
                'field' => 'id',
                'id' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'PRI',
            ),
            1 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Author',
                'edit' => 1,
                'field' => 'author_id',
                'id' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Title',
                'edit' => 1,
                'field' => 'title',
                'id' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'excerpt',
                'edit' => 1,
                'field' => 'excerpt',
                'id' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            4 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Body',
                'edit' => 1,
                'field' => 'body',
                'id' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'rich_text_box',
            ),
            5 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{
"resize": {
"width": "1000",
"height": "null"
},
"quality": "70%",
"upsize": true,
"thumbnails": [
{
"name": "medium",
"scale": "50%"
},
{
"name": "small",
"scale": "25%"
},
{
"name": "cropped",
"crop": {
"width": "300",
"height": "250"
}
}
]
}',
                'display_name' => 'Post Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            6 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"slugify": {"origin": "title", "forceUpdate": true}}',
                'display_name' => 'slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_description',
                'edit' => 1,
                'field' => 'meta_description',
                'id' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_keywords',
                'edit' => 1,
                'field' => 'meta_keywords',
                'id' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{
"default": "DRAFT",
"options": {
"PUBLISHED": "published",
"DRAFT": "draft",
"PENDING": "pending"
}
}',
                'display_name' => 'status',
                'edit' => 1,
                'field' => 'status',
                'id' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            12 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 13,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'author_id',
                'edit' => 0,
                'field' => 'author_id',
                'id' => 14,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            14 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'title',
                'edit' => 1,
                'field' => 'title',
                'id' => 15,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            15 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'excerpt',
                'edit' => 1,
                'field' => 'excerpt',
                'id' => 16,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'body',
                'edit' => 1,
                'field' => 'body',
                'id' => 17,
                'read' => 1,
                'required' => 1,
                'type' => 'rich_text_box',
            ),
            17 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '{"slugify": {"origin": "title"}}',
                'display_name' => 'slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 18,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            18 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_description',
                'edit' => 1,
                'field' => 'meta_description',
                'id' => 19,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_keywords',
                'edit' => 1,
                'field' => 'meta_keywords',
                'id' => 20,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '{
"default": "INACTIVE",
"options": {
"INACTIVE": "INACTIVE",
"ACTIVE": "ACTIVE"
}
}',
                'display_name' => 'status',
                'edit' => 1,
                'field' => 'status',
                'id' => 21,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            21 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 22,
                'read' => 1,
                'required' => 1,
                'type' => 'timestamp',
            ),
            22 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 23,
                'read' => 0,
                'required' => 1,
                'type' => 'timestamp',
            ),
            23 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'image',
                'edit' => 1,
                'field' => 'image',
                'id' => 24,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            24 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 25,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            25 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '',
                'display_name' => '用户名',
                'edit' => 1,
                'field' => 'name',
                'id' => 26,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            26 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '',
                'display_name' => 'email',
                'edit' => 1,
                'field' => 'email',
                'id' => 27,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            27 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'password',
                'edit' => 1,
                'field' => 'password',
                'id' => 28,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            28 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'remember_token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 29,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            29 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 30,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            30 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 31,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            31 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'avatar',
                'edit' => 0,
                'field' => 'avatar',
                'id' => 32,
                'read' => 0,
                'required' => 0,
                'type' => 'image',
            ),
            32 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 33,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            33 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '',
                'display_name' => 'name',
                'edit' => 1,
                'field' => 'name',
                'id' => 34,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            34 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 35,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            35 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 36,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            36 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 37,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            37 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{
"default": "__null__",
"null": "__null__",
"options": {
"__null__": "NULL"
},
"relationship": {
"key": "id",
"label": "name"
}
}',
                'display_name' => 'parent_id',
                'edit' => 1,
                'field' => 'parent_id',
                'id' => 38,
                'read' => 1,
                'required' => 0,
                'type' => 'select_dropdown',
            ),
            38 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{
"default": 1
}
',
                'display_name' => 'order',
                'edit' => 1,
                'field' => 'order',
                'id' => 39,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '',
                'display_name' => 'name',
                'edit' => 1,
                'field' => 'name',
                'id' => 40,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '',
                'display_name' => 'slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 41,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            41 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 42,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            42 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 43,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            43 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 44,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            44 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 45,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            45 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 46,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            46 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 47,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            47 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 48,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'seo_title',
                'edit' => 1,
                'field' => 'seo_title',
                'id' => 49,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            49 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'featured',
                'edit' => 1,
                'field' => 'featured',
                'id' => 50,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            50 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{"relationship":{"key":"id","label":"display_name","method":"role"}}',
                'display_name' => '角色',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 51,
                'read' => 1,
                'required' => 0,
                'type' => 'select_dropdown',
            ),
            51 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Usage',
                'edit' => 0,
                'field' => 'usage',
                'id' => 52,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            52 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Subscription Id',
                'edit' => 0,
                'field' => 'subscription_id',
                'id' => 53,
                'read' => 0,
                'required' => 0,
                'type' => 'checkbox',
            ),
            53 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Paypal Email',
                'edit' => 0,
                'field' => 'paypal_email',
                'id' => 54,
                'read' => 0,
                'required' => 0,
                'type' => 'checkbox',
            ),
            54 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Card Brand',
                'edit' => 0,
                'field' => 'card_brand',
                'id' => 55,
                'read' => 0,
                'required' => 0,
                'type' => 'checkbox',
            ),
            55 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Card Last Four',
                'edit' => 0,
                'field' => 'card_last_four',
                'id' => 56,
                'read' => 0,
                'required' => 0,
                'type' => 'checkbox',
            ),
            56 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Trial Ends At',
                'edit' => 0,
                'field' => 'trial_ends_at',
                'id' => 57,
                'read' => 0,
                'required' => 0,
                'type' => 'checkbox',
            ),
            57 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{"default":"0","options":{"0":"等待邮箱验证","1":"正常","2":"冻结"}}',
                'display_name' => '状态',
                'edit' => 1,
                'field' => 'state',
                'id' => 58,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            58 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Verify Token',
                'edit' => 0,
                'field' => 'verify_token',
                'id' => 59,
                'read' => 0,
                'required' => 0,
                'type' => 'checkbox',
            ),
            59 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Expired',
                'edit' => 1,
                'field' => 'expired',
                'id' => 60,
                'read' => 1,
                'required' => 1,
                'type' => 'timestamp',
            ),
            60 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 61,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            61 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 62,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            62 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '',
                'display_name' => '创建时间',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 63,
                'read' => 0,
                'required' => 0,
                'type' => 'date',
            ),
            63 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '',
                'display_name' => '更新时间',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 64,
                'read' => 0,
                'required' => 0,
                'type' => 'date',
            ),
            64 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '',
                'display_name' => ' 分组',
                'edit' => 1,
                'field' => 'category',
                'id' => 65,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            65 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 66,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            66 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 67,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            67 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"validation":{"rule":"min:6"}}',
                'display_name' => '密码',
                'edit' => 1,
                'field' => 'password',
                'id' => 68,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            68 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '',
                'display_name' => '电话',
                'edit' => 1,
                'field' => 'telephone',
                'id' => 69,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            69 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '',
                'display_name' => '地址',
                'edit' => 1,
                'field' => 'address',
                'id' => 70,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            70 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"description":"默认生成10位随机码，有效期7天，如果要修改有效期，在随机数末尾加2位数字。比如ycpOG2AAIb20表示20天有效期。"}',
                'display_name' => '跟踪码',
                'edit' => 1,
                'field' => 'track',
                'id' => 71,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            71 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"default":"0","options":{"0":"禁用","1":"启用"}}',
                'display_name' => '状态',
                'edit' => 1,
                'field' => 'status',
                'id' => 72,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            72 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"default":0,"options":{"0":"CPC","1":"CPA"}}',
                'display_name' => '',
                'edit' => 1,
                'field' => 'type',
                'id' => 73,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            73 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '',
                'display_name' => '分成',
                'edit' => 0,
                'field' => 'share',
                'id' => 74,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            74 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '',
                'display_name' => '余额',
                'edit' => 0,
                'field' => 'balance',
                'id' => 75,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            75 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '',
                'display_name' => '创建时间',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 77,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            76 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '',
                'display_name' => '更新时间',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 78,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            77 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '',
                'display_name' => '点击次数',
                'edit' => 0,
                'field' => 'click',
                'id' => 79,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            78 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '',
                'display_name' => '',
                'edit' => 0,
                'field' => 'action',
                'id' => 80,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            79 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '',
                'display_name' => '名称',
                'edit' => 1,
                'field' => 'name',
                'id' => 81,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            80 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 82,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            81 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '',
                'display_name' => '名称',
                'edit' => 1,
                'field' => 'name',
                'id' => 83,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            82 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '',
                'display_name' => '折扣码',
                'edit' => 1,
                'field' => 'code',
                'id' => 84,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            83 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{"default":"0","options":{"0":"百分比","1":"固定金额"}}',
                'display_name' => '类型',
                'edit' => 1,
                'field' => 'type',
                'id' => 85,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            84 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{"description":"如果类型是固定金额，该值为固定金额;如果是百分比，范围应该在10~100，按百分比优惠"}',
                'display_name' => '折扣',
                'edit' => 1,
                'field' => 'discount',
                'id' => 86,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            85 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '',
                'display_name' => '满减金额',
                'edit' => 1,
                'field' => 'total',
                'id' => 87,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            86 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '',
                'display_name' => '起始日期',
                'edit' => 1,
                'field' => 'start',
                'id' => 88,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            87 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '',
                'display_name' => '结束日期',
                'edit' => 1,
                'field' => 'end',
                'id' => 89,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            88 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '',
                'display_name' => '总数',
                'edit' => 1,
                'field' => 'uses',
                'id' => 90,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            89 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '',
                'display_name' => '每个客户可使用数量',
                'edit' => 1,
                'field' => 'customer_uses',
                'id' => 91,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            90 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '',
                'display_name' => '已使用',
                'edit' => 0,
                'field' => 'used',
                'id' => 92,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            91 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{"default":"0","options":{"0":"禁用","1":"启用"}}',
                'display_name' => '状态',
                'edit' => 1,
                'field' => 'status',
                'id' => 93,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            92 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '',
                'display_name' => '创建时间',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 94,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            93 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '',
                'display_name' => '更新时间',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 95,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            94 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '',
                'display_name' => '编号',
                'edit' => 0,
                'field' => 'id',
                'id' => 96,
                'read' => 1,
                'required' => 1,
                'type' => 'PRI',
            ),
            95 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '',
                'display_name' => '支付定单',
                'edit' => 0,
                'field' => 'payment_id',
                'id' => 97,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            96 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '',
                'display_name' => '金额',
                'edit' => 1,
                'field' => 'amount',
                'id' => 98,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            97 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '{"default":"created","options":{"created":"Created","pending":"Pending","accepted":"accepted","rejected":"rejected"}}',
                'display_name' => '状态',
                'edit' => 0,
                'field' => 'status',
                'id' => 99,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            98 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '',
                'display_name' => '备注',
                'edit' => 1,
                'field' => 'note',
                'id' => 100,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            99 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '',
                'display_name' => '创建时间',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 101,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            100 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '',
                'display_name' => '更新时间',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 102,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            101 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '',
                'display_name' => '支付网关退款编号',
                'edit' => 0,
                'field' => 'remote_number',
                'id' => 103,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            102 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Affiliate Id',
                'edit' => 0,
                'field' => 'affiliate_id',
                'id' => 104,
                'read' => 0,
                'required' => 1,
                'type' => 'checkbox',
            ),
            103 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Regip',
                'edit' => 0,
                'field' => 'regip',
                'id' => 105,
                'read' => 1,
                'required' => 0,
                'type' => 'checkbox',
            ),
            104 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Edm',
                'edit' => 0,
                'field' => 'edm',
                'id' => 106,
                'read' => 0,
                'required' => 1,
                'type' => 'checkbox',
            ),
            105 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Tag',
                'edit' => 1,
                'field' => 'tag',
                'id' => 107,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            106 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 108,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            107 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '',
                'display_name' => '键值',
                'edit' => 1,
                'field' => 'key',
                'id' => 109,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            108 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '',
                'display_name' => '表格名称',
                'edit' => 1,
                'field' => 'table_name',
                'id' => 110,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            109 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '',
                'display_name' => '描述',
                'edit' => 1,
                'field' => 'desc',
                'id' => 111,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            110 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '',
                'display_name' => '顺序',
                'edit' => 1,
                'field' => 'order',
                'id' => 112,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            111 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '',
                'display_name' => '创建时间',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 113,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            112 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '',
                'display_name' => '修改时间',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 114,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            113 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 115,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            114 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Key',
                'edit' => 1,
                'field' => 'key',
                'id' => 116,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            115 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 1,
                'details' => '{"default":"0","options":{"0":"永久累计","1":"按月累计","2":"按日累计","3":"按小时累计","4":"数值","5":"周期值","6":"按年累计"}}',
                'display_name' => '类型',
                'edit' => 1,
                'field' => 'type',
                'id' => 117,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            116 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '',
                'display_name' => '创建时间',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 118,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            117 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 16,
                'delete' => 1,
                'details' => '',
                'display_name' => '更新时间',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 119,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            118 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 120,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            119 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{"relationship":{"key":"id","label":"display_name","method":"role"}}',
                'display_name' => '角色',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 121,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            120 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '唯一标识',
                'edit' => 1,
                'field' => 'name',
                'id' => 122,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            121 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '显示名称',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 123,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            122 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '描述',
                'edit' => 1,
                'field' => 'desc',
                'id' => 124,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            123 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '显示顺序',
                'edit' => 1,
                'field' => 'display_order',
                'id' => 125,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            124 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{"default":"REGULAR"}',
                'display_name' => '类型',
                'edit' => 1,
                'field' => 'type',
                'id' => 126,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            125 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '计费周期类型',
                'edit' => 1,
                'field' => 'frequency',
                'id' => 127,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            126 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '计费周期',
                'edit' => 1,
                'field' => 'frequency_interval',
                'id' => 128,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            127 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '扣费次数',
                'edit' => 1,
                'field' => 'cycles',
                'id' => 129,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            128 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '{"step":0.01}',
                'display_name' => '价格',
                'edit' => 1,
                'field' => 'amount',
                'id' => 130,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            129 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '货币类型',
                'edit' => 1,
                'field' => 'currency',
                'id' => 131,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            130 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Paypal Id',
                'edit' => 1,
                'field' => 'paypal_id',
                'id' => 132,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            131 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 17,
                'delete' => 0,
                'details' => '',
                'display_name' => '创建时间',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 133,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            132 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Updated At',
                'edit' => 1,
                'field' => 'updated_at',
                'id' => 134,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            133 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '建立费用',
                'edit' => 1,
                'field' => 'setup_fee',
                'id' => 135,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            134 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => '延迟天数',
                'edit' => 1,
                'field' => 'delay_days',
                'id' => 136,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            135 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 17,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 137,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            136 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 18,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 138,
                'read' => 0,
                'required' => 1,
                'type' => 'PRI',
            ),
            137 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 18,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Gateway Name',
                'edit' => 1,
                'field' => 'gateway_name',
                'id' => 139,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            138 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 18,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Factory Name',
                'edit' => 1,
                'field' => 'factory_name',
                'id' => 140,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            139 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 18,
                'delete' => 1,
                'details' => '{"json":true,"description":"Must be strict json string"}',
                'display_name' => 'Config',
                'edit' => 1,
                'field' => 'config',
                'id' => 141,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            140 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 18,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 142,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            141 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 18,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 143,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            142 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Custom Option',
                'edit' => 0,
                'field' => 'custom_option',
                'id' => 144,
                'read' => 0,
                'required' => 0,
                'type' => 'checkbox',
            ),
            143 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Is Check',
                'edit' => 0,
                'field' => 'is_check',
                'id' => 145,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            144 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{"null":""}',
                'display_name' => 'Session Count',
                'edit' => 1,
                'field' => 'session_count',
                'id' => 146,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            145 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{"null":""}',
                'display_name' => 'Session Ip Count',
                'edit' => 1,
                'field' => 'session_ip_count',
                'id' => 147,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            146 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Subscription Email',
                'edit' => 1,
                'field' => 'subscription_email',
                'id' => 148,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
        ));
        
        
    }
}