<?php

use Illuminate\Database\Seeder;

class PlansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('plans')->delete();
        
        \DB::table('plans')->insert(array (
            0 => 
            array (
                'id' => 69,
                'role_id' => 3,
                'name' => 'free',
                'display_name' => 'Free Level',
                'desc' => 'Free Plan',
                'display_order' => 0,
                'type' => 'REGULAR',
                'frequency' => 'YEAR',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 0.0,
                'currency' => 'USD',
                'paypal_id' => '',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2017-12-15 03:08:58',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'free',
            ),
            1 => 
            array (
                'id' => 70,
                'role_id' => 3,
                'name' => 'free_monthly',
                'display_name' => 'Free Level',
                'desc' => 'Free Plan for an month',
                'display_order' => 0,
                'type' => 'REGULAR',
                'frequency' => 'MONTH',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 0.0,
                'currency' => 'USD',
                'paypal_id' => '',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2017-12-13 19:08:00',
                'setup_fee' => 0.0,
                'delay_days' => 0,
                'slug' => 'free_monthly',
            ),
            2 => 
            array (
                'id' => 71,
                'role_id' => 10,
                'name' => 'lite_monthly',
                'display_name' => 'Lite Monthly',
                'desc' => 'Lite Plan for one month',
                'display_order' => 1,
                'type' => 'REGULAR',
                'frequency' => 'MONTH',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 99.0,
                'currency' => 'USD',
                'paypal_id' => 'P-6FL441960U836971YN45BPYY',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-06 07:45:00',
                'setup_fee' => 0.0,
                'delay_days' => 0,
                'slug' => 'lite_monthly',
            ),
            3 => 
            array (
                'id' => 72,
                'role_id' => 10,
                'name' => 'lite_quarterly',
                'display_name' => 'Lite Quarterly',
                'desc' => 'Lite Plan for three month',
                'display_order' => 1,
                'type' => 'REGULAR',
                'frequency' => 'MONTH',
                'frequency_interval' => 3,
                'cycles' => 0,
                'amount' => 119.97,
                'currency' => 'USD',
                'paypal_id' => 'P-8BJ523814W4157934N45CJUI',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-07 15:45:54',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'lite_quarterly',
            ),
            4 => 
            array (
                'id' => 73,
                'role_id' => 10,
                'name' => 'lite_annual',
                'display_name' => 'Lite Annual',
                'desc' => 'Lite Plan for one year',
                'display_order' => 1,
                'type' => 'REGULAR',
                'frequency' => 'YEAR',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 299.88,
                'currency' => 'USD',
                'paypal_id' => 'P-4S38852773223621LN45EKFA',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-07 15:46:02',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'lite_annual',
            ),
            5 => 
            array (
                'id' => 74,
                'role_id' => 4,
                'name' => 'standard_monthly',
                'display_name' => 'Standard Monthly',
                'desc' => 'standard  Plan for one month',
                'display_order' => 2,
                'type' => 'REGULAR',
                'frequency' => 'MONTH',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 149.0,
                'currency' => 'USD',
                'paypal_id' => 'P-9X2589948R7221534N45FEIQ',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-06 23:46:00',
                'setup_fee' => 0.0,
                'delay_days' => 0,
                'slug' => 'standard_monthly',
            ),
            6 => 
            array (
                'id' => 75,
                'role_id' => 4,
                'name' => 'standard_quarter_monthly',
                'display_name' => 'Standard Quarterly',
                'desc' => 'standard  Plan for three months',
                'display_order' => 2,
                'type' => 'REGULAR',
                'frequency' => 'MONTH',
                'frequency_interval' => 3,
                'cycles' => 0,
                'amount' => 237.0,
                'currency' => 'USD',
                'paypal_id' => 'P-79493643CM609072GN45HEUQ',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-07 15:46:14',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'standard_quarterly',
            ),
            7 => 
            array (
                'id' => 76,
                'role_id' => 4,
                'name' => 'standard',
                'display_name' => 'Standard Annual',
                'desc' => 'standard  Plan for one year',
                'display_order' => 2,
                'type' => 'REGULAR',
                'frequency' => 'YEAR',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 780.0,
                'currency' => 'USD',
                'paypal_id' => 'P-21551737CA962540KN45H4UQ',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-07 15:46:17',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'standard_annual',
            ),
            8 => 
            array (
                'id' => 77,
                'role_id' => 5,
                'name' => 'advanced_monthly',
                'display_name' => 'Plus Plan',
                'desc' => 'Plus Plan for one month',
                'display_order' => 3,
                'type' => 'REGULAR',
                'frequency' => 'MONTH',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 179.0,
                'currency' => 'USD',
                'paypal_id' => 'P-6C078973NL345825CN45IVBA',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-06 23:46:00',
                'setup_fee' => 0.0,
                'delay_days' => 0,
                'slug' => 'advanced_monthly',
            ),
            9 => 
            array (
                'id' => 78,
                'role_id' => 5,
                'name' => 'advanced',
                'display_name' => 'advanced Plan',
                'desc' => 'advanced Plan for one year',
                'display_order' => 3,
                'type' => 'REGULAR',
                'frequency' => 'YEAR',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 1668.0,
                'currency' => 'USD',
                'paypal_id' => 'P-1YC677039F168652NN45KVDQ',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-07 15:46:28',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'advanced',
            ),
            10 => 
            array (
                'id' => 79,
                'role_id' => 6,
                'name' => 'vip_monthly',
                'display_name' => 'vip Plan',
                'desc' => 'vip Plan for one month',
                'display_order' => 4,
                'type' => 'REGULAR',
                'frequency' => 'MONTH',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 299.0,
                'currency' => 'USD',
                'paypal_id' => 'P-1WC43476Y69553218N45LNVA',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-07 15:46:31',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'vip_monthly',
            ),
            11 => 
            array (
                'id' => 80,
                'role_id' => 6,
                'name' => 'vip',
                'display_name' => 'vip Plan',
                'desc' => 'vip Plan for one year',
                'display_order' => 4,
                'type' => 'REGULAR',
                'frequency' => 'YEAR',
                'frequency_interval' => 1,
                'cycles' => 0,
                'amount' => 3588.0,
                'currency' => 'USD',
                'paypal_id' => 'P-6D272746XT099721VN45NOAY',
                'created_at' => '2017-12-15 03:08:58',
                'updated_at' => '2018-02-07 15:46:40',
                'setup_fee' => NULL,
                'delay_days' => 0,
                'slug' => 'vip',
            ),
        ));
        
        
    }
}